services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_django_project.wsgi
    envVars:
      - key: SECRET_KEY
        value: your-secret
      - key: DB_PASSWORD
        value: Raheemah123&
      - key: DB_HOST
        value: db.lfozhukosevtobcxtnse.supabase.co
      - key: DJANGO_SETTINGS_MODULE
        value: your_django_project.settings

  - type: static
    name: frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://your-backend.onrender.com/api/
