services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DB_PASSWORD
        value: your_supabase_db_password
      - key: DB_HOST
        value: your_supabase_host.supabase.co
